version: '3'

services:
  espacios: 
    build: ./espacios
  servicios: 
    build: ./servicios
    depends_on:
      - mongo
    environment:
      - MONGODB_CNN5=mongodb://mongo:27017/microservicesespacios
      - MONGODB_CNN6=mongodb://mongo:27017/microservicesservicios
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - espacios
      - servicios
